const ContactForm = require("../models/contactFormModel");
const asyncHandler = require("../utils/asyncHandler");
const ApiResponse = require("../utils/apiResponse");
const ApiError = require("../utils/apiError");
const sendEmail = require("../utils/sendEmail");

// 📝 POST: Create new contact form submission
exports.createContactForm = asyncHandler(async (req, res) => {
try {
const { name, company, email, phone, requirement, type } = req.body;

if (!email) {
throw new ApiError(400, "Email is required");
}

// ✅ Step 1: Save form data in DB_
const newForm = await ContactForm.create({
name,
company,
email,
phone,
requirement,
type,
});

// ✅ Step 2: Prepare email content_
let subject = "";
let htmlContent = "";

if (type === "enquiry") {
subject = "📩 New Enquiry Received - Siara Technology";
htmlContent = `
<h2>📝 New Enquiry Form Submission</h2>
<p><b>Name:</b> ${name || "N/A"}</p>
<p><b>Company:</b> ${company || "N/A"}</p>
<p><b>Email:</b> ${email}</p>
<p><b>Phone:</b> ${phone || "N/A"}</p>
<p><b>Requirement:</b> ${requirement || "N/A"}</p>
<p><b>Type:</b> ${type}</p>
<hr />
<p style="font-size: 13px; color: #888;">
This email was automatically generated by Siara Technology’s contact form.
</p>
`;
} else if (type === "subscriber") {
subject = "🆕 New Newsletter Subscriber - Siara Technology";
htmlContent = `
<h2>📬 New User Subscribed!</h2>
<p><b>Email:</b> ${email}</p>
<p>A new user has subscribed to the Siara Technology newsletter.</p>
<hr />
<p style="font-size: 13px; color: #888;">
This notification was generated automatically by your website.
</p>
`;
} else {
subject = "📨 New Contact Form - Siara Technology";
htmlContent = `
<h2>Contact Form Submission</h2>
<p><b>Email:</b> ${email}</p>
<p><b>Type:</b> ${type || "N/A"}</p>
`;
}

_// ✅ Step 3: Send internal email_
const response = await sendEmail({
to: process.env.ZOHO_USER_RECIVER,
subject,
html: htmlContent,
});

console.log("📨 Email sent:", response);

// ✅ Step 4: Respond to client_
res
.status(201)
.json(new ApiResponse(201, newForm, "Contact form submitted successfully"));
} catch (error) {
console.error("❌ Error in createContactForm:", error);
throw new ApiError(500, "Failed to process contact form submission");
}
});

// 📄 GET: Get all submissions (for dashboard/admin)
exports.getAllContactForms = asyncHandler(async (req, res) => {
  const forms = await ContactForm.find().sort({ createdAt: -1 });
  res
    .status(200)
    .json(new ApiResponse(200, forms, "All contact forms fetched successfully"));
});

// 🧾 GET: Get single submission by ID
exports.getContactFormById = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const form = await ContactForm.findById(id);

  if (!form) throw new ApiError(404, "Contact form not found");

  res
    .status(200)
    .json(new ApiResponse(200, form, "Contact form fetched successfully"));
});

// 🗑️ DELETE: Delete submission
exports.deleteContactForm = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const deleted = await ContactForm.findByIdAndDelete(id);

  if (!deleted) throw new ApiError(404, "Contact form not found");

  res
    .status(200)
    .json(new ApiResponse(200, null, "Contact form deleted successfully"));
});
